### PR TITLE
Added monitoring query

### PR DESCRIPTION
**Pull request by alexey-rise**
@tejohnso please review.

Unfortunately this cannot be made into a view, the whole thing would have to be on the monitoring server.

For now the query is set up to use dummy data so that it can be used in testing, production data is not available yet. Once it  is the three commented out lines in the query would need to be uncommented and the test lines deleted.

### CODE REVIEW

**Comment by tejohnso** [comment]
@alexey-rise That looks great, I'm liking the standardSQL features. I think we can keep the query in the [display monitoring](https://github.com/Rise-Vision/display-monitoring-server) repo if it's not going to be made into a view managed from the BQ console.

Few questions:

 1 Can you confirm that we don't have to worry about excessive growth on these tables? The query is going through roughly 200MB right now. I'm guessing that should scale fairly linearly with display growth.

2  Regarding the displayAuthorizations section can you clarify why the display index of the playerProAssignedDisplays is used? Are we arbitrarily taking as many as we can from the top rather than the bottom or is that order significant and maintained in the table by Core?

3 How can there be more playerProAssignedDisplays than there are totalLicenses? Is it because we don't unassign displays when licenses are no longer valid? I thought I had read a plan to automatically unassign displays based on most recent entry date when license count is reduced.

4 The companySubscriptions table was just created on Feb2. How does it relate to existing store tables? How come we're not using existing tables?

**Comment by alexey-rise** [comment]
@tejohnso please let me know where in [display monitoring](https://github.com/Rise-Vision/display-monitoring-server) repo you want me to move the query to and I'll move it.
To answer your questions:
>Can you confirm that we don't have to worry about excessive growth on these tables? The query is going through roughly 200MB right now. I'm guessing that should scale fairly linearly with display growth.

Yes, I believe the BQ billable data should grow linearly (or better) with the size of the `displays` table. This table has an average of ~9 records per displayID, it has no frequently updated information (similar to user last login etc). 
Interestingly enough when I run the query for `appId='dummy'` BQ goes through only about 14K records in `displays` table (with total billable data of ~198Mb) but when I set `appId='s~rvaserver2'` BQ looks through all 1.8M records yet total billable data remains essentially the same (199Mb).

>Regarding the displayAuthorizations section can you clarify why the display index of the playerProAssignedDisplays is used? Are we arbitrarily taking as many as we can from the top rather than the bottom or is that order significant and maintained in the table by Core?

The order is important and is defined in the [display licensing design](https://docs.google.com/document/d/10_xP59GGw4rI2KJJzrEgVxua3uq_R6cWGKMYleUoSCs/edit?usp=sharing):
image
I am using the order as stored in the Core DB (and as exported by the Core to BQ) This is one of the reasons I need to use JavaScript in this query.

>How can there be more playerProAssignedDisplays than there are totalLicenses? Is it because we don't unassign displays when licenses are no longer valid? I thought I had read a plan to automatically unassign displays based on most recent entry date when license count is reduced.

Please refer to @alex-deaconu re this, I am simply repeating the logic already being used in the Store to authorize displays in the new system.

>The companySubscriptions table was just created on Feb2. How does it relate to existing store/core tables? How come we're not using existing tables?

I created that table, it is a BQ export destination for the new CompanySubscriptions table from Core DB. We are moving display authorization from the Store to Apps (as per [display licensing design](https://docs.google.com/document/d/10_xP59GGw4rI2KJJzrEgVxua3uq_R6cWGKMYleUoSCs/edit?usp=sharing)). It greatly simplified my query BTW.

**Comment by tejohnso** [comment]
@santiagonoguez any preference where this goes for the query runner to read it?

**Comment by santiagonoguez** [comment]
@tejohnso placing it below some directory like src/queries would work fine I guess.

**Comment by tejohnso** [comment]
@alexey-rise 
@santiagonoguez has integrated this query into his branch on display monitoring, so I'm closing this PR.

**Pull request closed without merging**
